[build]
  functions = "netlify/functions"

[build.environment]
  CLOUDINARY_API_SECRET = "Lw4Ly5RM6FDlef_1q85Jtha3TLs"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
